---
title: "Exercise 1 Carlos Fabbri"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Read the data

```{r}
data = read.csv('Connections.csv', encoding = 'UTF-8')

```


```{r}
library(dplyr)

data %>% group_by(Company) %>% count() %>% arrange(desc(n))

```


```{r results='hide'}
names(data)
```


```{r}
library(tidyverse)
library(tidygraph)
library(ggraph)

data$Last_name_initial = substr(data$Last.Name, 1,1)


data = data %>% mutate(
  name = paste(First.Name, Last_name_initial, sep = " ")
)

data$index <- 1:nrow(data)

nodes <- data %>% select(c("name", "Company"))

nodes <- nodes %>% rowid_to_column("id")

edges <- data %>% select(c(name, Company)) %>% 
  left_join(nodes %>% select(c(id,name)), by = c("name"="name"))

edges <- edges %>% left_join(edges, by = "Company", keep=FALSE) %>% 
  select(c("id.x", "id.y", "Company")) %>% 
  filter(id.x!=id.y)


colnames(edges) <- c("x", "y", "Company")

graph <- tbl_graph(edges = edges, nodes=nodes, directed = FALSE)

ggraph(graph, layout = "graphopt") + 
  geom_edge_link( show.legend = FALSE) + 
  geom_node_point()+
  theme_graph()
```

## Another method using network library

```{r results='hide'}



df1 <- data.frame()

# iterate through each company and generate the edges 
for (company in unique(data$Company) ){
  
company_edges = data %>% filter(Company==company) %>% pull(index)

edges = expand.grid(company_edges, company_edges)

# remove the connections with themselves
edges = edges %>% filter(Var1 != Var2)

# append to main df1
df1 <- rbind(df1, edges)

#print(dim(df1))
  
}

# nodes = data$index
# edges = df1

df1$temp <- apply(df1, 1, function(x) paste(sort(x), collapse=""))

df1 = df1[!duplicated(df1$temp), 1:2] # remove duplicate (each combination appears once)

df1
```


```{r}
library(tidygraph)
#install.packages('network')
library(network)


linkedin_network <- network(df1, attr = data,  matrix.type = "edgelist",directed=FALSE)

linkedin_network

plot(linkedin_network )

#to do: print names of nodes
```


  

